netbox_slm/urls.py
from django.urls import path, include

from netbox_slm import views  # noqa F401
from utilities.urls import get_model_urls

urlpatterns = [
    path("software-products/", include(get_model_urls("netbox_slm", "softwareproduct", detail=False))),
    path("software-products/<int:pk>/", include(get_model_urls("netbox_slm", "softwareproduct"))),
    path("versions/", include(get_model_urls("netbox_slm", "softwareproductversion", detail=False))),
    path("versions/<int:pk>/", include(get_model_urls("netbox_slm", "softwareproductversion"))),
    path("installations/", include(get_model_urls("netbox_slm", "softwareproductinstallation", detail=False))),
    path("installations/<int:pk>/", include(get_model_urls("netbox_slm", "softwareproductinstallation"))),
    path("licenses/", include(get_model_urls("netbox_slm", "softwarelicense", detail=False))),
    path("licenses/<int:pk>/", include(get_model_urls("netbox_slm", "softwarelicense"))),
]

netbox_slm/models.py
from django.core.exceptions import ValidationError
from django.db import models
from django.urls import reverse
from django.utils.html import format_html, urlencode
from license_expression import Licensing, get_spdx_licensing

from netbox.models import NetBoxModel
from utilities.querysets import RestrictedQuerySet
from utilities.validators import EnhancedURLValidator

spdx_licensing: Licensing = get_spdx_licensing()


class LaxURLField(models.URLField):
    """
    NetBox Custom Field approach, based on utilities.forms.fields.LaxURLField
    Overriding default_validators is needed, as they are always added
    """

    default_validators = [EnhancedURLValidator()]


class SoftwareProduct(NetBoxModel):
    name = models.CharField(max_length=128)
    comments = models.TextField(blank=True)

    description = models.CharField(max_length=255, null=True, blank=True)
    manufacturer = models.ForeignKey(to="dcim.Manufacturer", on_delete=models.PROTECT, null=True, blank=True)

    objects = RestrictedQuerySet.as_manager()

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("plugins:netbox_slm:softwareproduct", kwargs={"pk": self.pk})

    def get_installation_count(self):
        count = SoftwareProductInstallation.objects.filter(software_product_id=self.pk).count()
        query_string = urlencode(dict(software_product_id=self.pk))
        search_target = reverse("plugins:netbox_slm:softwareproductinstallation_list")
        # Can be composed directly with reverse(query=) in Django 5.2, see https://code.djangoproject.com/ticket/25582
        return format_html(f"<a href='{search_target}?{query_string}'>{count}</a>") if count else "0"


class SoftwareReleaseTypes(models.TextChoices):
    ALPHA = "A", "Alpha"
    BETA = "B", "Beta"
    RELEASE_CANDIDATE = "RC", "Release candidate"
    STABLE = "S", "Stable release"


class SoftwareProductVersion(NetBoxModel):
    name = models.CharField(max_length=64)
    comments = models.TextField(blank=True)

    description = models.CharField(max_length=255, null=True, blank=True)
    release_date = models.DateField(null=True, blank=True)
    documentation_url = LaxURLField(max_length=1024, null=True, blank=True)
    end_of_support = models.DateField(null=True, blank=True)
    filename = models.CharField(max_length=64, null=True, blank=True)
    file_checksum = models.CharField(max_length=128, null=True, blank=True)
    file_link = LaxURLField(max_length=1024, null=True, blank=True)

    release_type = models.CharField(
        max_length=3,
        choices=SoftwareReleaseTypes.choices,
        default=SoftwareReleaseTypes.STABLE,
    )

    software_product = models.ForeignKey(
        to="netbox_slm.SoftwareProduct",
        on_delete=models.PROTECT,
    )

    objects = RestrictedQuerySet.as_manager()

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("plugins:netbox_slm:softwareproductversion", kwargs={"pk": self.pk})

    def get_installation_count(self):
        count = SoftwareProductInstallation.objects.filter(version_id=self.pk).count()
        query_string = urlencode(dict(version_id=self.pk))
        search_target = reverse("plugins:netbox_slm:softwareproductinstallation_list")
        # Can be composed directly with reverse(query=) in Django 5.2, see https://code.djangoproject.com/ticket/25582
        return format_html(f"<a href='{search_target}?{query_string}'>{count}</a>") if count else "0"


class SoftwareProductInstallation(NetBoxModel):
    comments = models.TextField(blank=True)

    device = models.ForeignKey(to="dcim.Device", on_delete=models.PROTECT, null=True, blank=True)
    virtualmachine = models.ForeignKey(
        to="virtualization.VirtualMachine", on_delete=models.PROTECT, null=True, blank=True
    )
    cluster = models.ForeignKey(to="virtualization.Cluster", on_delete=models.PROTECT, null=True, blank=True)
    software_product = models.ForeignKey(to="netbox_slm.SoftwareProduct", on_delete=models.PROTECT)
    version = models.ForeignKey(to="netbox_slm.SoftwareProductVersion", on_delete=models.PROTECT)

    objects = RestrictedQuerySet.as_manager()

    def __str__(self):
        return f"{self.pk} ({self.platform})"

    class Meta:
        constraints = [
            models.CheckConstraint(
                name="%(app_label)s_%(class)s_platform",
                check=(
                    models.Q(device__isnull=False, virtualmachine__isnull=True, cluster__isnull=True)
                    | models.Q(device__isnull=True, virtualmachine__isnull=False, cluster__isnull=True)
                    | models.Q(device__isnull=True, virtualmachine__isnull=True, cluster__isnull=False)
                ),
                violation_error_message="Installation requires exactly one platform destination.",
            )
        ]

    def get_absolute_url(self):
        return reverse("plugins:netbox_slm:softwareproductinstallation", kwargs={"pk": self.pk})

    @property
    def platform(self):
        return self.device or self.virtualmachine or self.cluster

    def render_type(self):
        if self.device:
            return "device"
        if self.virtualmachine:
            return "virtualmachine"
        return "cluster"


def spdx_license_names():
    names = [(item[0], item[0]) for item in spdx_licensing.known_symbols.items() if not item[1].is_exception]
    names.sort()
    names.insert(0, ("", "---------"))  # set default value
    return names


def validate_spdx_expression(value):
    expression_info = spdx_licensing.validate(value)
    if expression_info.errors:
        raise ValidationError(f"{value} is not a known SPDX license expression")


class SoftwareLicense(NetBoxModel):
    name = models.CharField(max_length=128)
    comments = models.TextField(blank=True)

    description = models.CharField(max_length=255, null=True, blank=True)
    type = models.CharField(max_length=128)
    spdx_expression = models.CharField(max_length=64, null=True, blank=True, validators=[validate_spdx_expression])
    stored_location = models.CharField(max_length=255, null=True, blank=True)
    stored_location_url = LaxURLField(max_length=1024, null=True, blank=True)
    start_date = models.DateField(null=True, blank=True)
    expiration_date = models.DateField(null=True, blank=True)
    support = models.BooleanField(default=None, null=True, blank=True)
    license_amount = models.PositiveIntegerField(default=None, null=True, blank=True)

    software_product = models.ForeignKey(to="netbox_slm.SoftwareProduct", on_delete=models.PROTECT)
    version = models.ForeignKey(to="netbox_slm.SoftwareProductVersion", on_delete=models.PROTECT, null=True, blank=True)
    installation = models.ForeignKey(
        to="netbox_slm.SoftwareProductInstallation", on_delete=models.SET_NULL, null=True, blank=True
    )

    objects = RestrictedQuerySet.as_manager()

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("plugins:netbox_slm:softwarelicense", kwargs={"pk": self.pk})

    @property
    def stored_location_txt(self):
        if self.stored_location_url and not self.stored_location:
            return "Link"
        return self.stored_location

netbox_slm/views/software_license.py
from netbox.views import generic
from netbox_slm import filtersets, forms, tables
from netbox_slm.models import SoftwareLicense
from utilities.views import register_model_view


@register_model_view(SoftwareLicense, "list", path="", detail=False)
class SoftwareLicenseListView(generic.ObjectListView):
    queryset = SoftwareLicense.objects.all()
    filterset = filtersets.SoftwareLicenseFilterSet
    filterset_form = forms.SoftwareLicenseFilterForm
    table = tables.SoftwareLicenseTable


@register_model_view(SoftwareLicense)
class SoftwareLicenseView(generic.ObjectView):
    queryset = SoftwareLicense.objects.all()


@register_model_view(SoftwareLicense, "add", detail=False)
@register_model_view(SoftwareLicense, "edit")
class SoftwareLicenseEditView(generic.ObjectEditView):
    queryset = SoftwareLicense.objects.all()
    form = forms.SoftwareLicenseForm


@register_model_view(SoftwareLicense, "delete")
class SoftwareLicenseDeleteView(generic.ObjectDeleteView):
    queryset = SoftwareLicense.objects.all()


@register_model_view(SoftwareLicense, "bulk_import", detail=False)
class SoftwareLicenseBulkImportView(generic.BulkImportView):
    queryset = SoftwareLicense.objects.all()
    model_form = forms.SoftwareLicenseBulkImportForm


@register_model_view(SoftwareLicense, "bulk_edit", path="edit", detail=False)
class SoftwareLicenseBulkEditView(generic.BulkEditView):
    queryset = SoftwareLicense.objects.all()
    filterset = filtersets.SoftwareLicenseFilterSet
    table = tables.SoftwareLicenseTable
    form = forms.SoftwareLicenseBulkEditForm


@register_model_view(SoftwareLicense, "bulk_delete", path="delete", detail=False)
class SoftwareLicenseBulkDeleteView(generic.BulkDeleteView):
    queryset = SoftwareLicense.objects.all()
    filterset = filtersets.SoftwareLicenseFilterSet
    table = tables.SoftwareLicenseTable

netbox_slm/views/software_product.py
from netbox.views import generic
from netbox_slm import filtersets, forms, tables
from netbox_slm.models import SoftwareProduct
from utilities.views import register_model_view


@register_model_view(SoftwareProduct, "list", path="", detail=False)
class SoftwareProductListView(generic.ObjectListView):
    queryset = SoftwareProduct.objects.all()
    filterset = filtersets.SoftwareProductFilterSet
    filterset_form = forms.SoftwareProductFilterForm
    table = tables.SoftwareProductTable


@register_model_view(SoftwareProduct)
class SoftwareProductView(generic.ObjectView):
    queryset = SoftwareProduct.objects.all()

    def get_extra_context(self, request, instance):
        versions = instance.softwareproductversion_set.all()
        return {"versions": versions}


@register_model_view(SoftwareProduct, "add", detail=False)
@register_model_view(SoftwareProduct, "edit")
class SoftwareProductEditView(generic.ObjectEditView):
    queryset = SoftwareProduct.objects.all()
    form = forms.SoftwareProductForm


@register_model_view(SoftwareProduct, "delete")
class SoftwareProductDeleteView(generic.ObjectDeleteView):
    queryset = SoftwareProduct.objects.all()


@register_model_view(SoftwareProduct, "bulk_import", detail=False)
class SoftwareProductBulkImportView(generic.BulkImportView):
    queryset = SoftwareProduct.objects.all()
    model_form = forms.SoftwareProductBulkImportForm


@register_model_view(SoftwareProduct, "bulk_edit", path="edit", detail=False)
class SoftwareProductBulkEditView(generic.BulkEditView):
    queryset = SoftwareProduct.objects.all()
    filterset = filtersets.SoftwareProductFilterSet
    table = tables.SoftwareProductTable
    form = forms.SoftwareProductBulkEditForm


@register_model_view(SoftwareProduct, "bulk_delete", path="delete", detail=False)
class SoftwareProductBulkDeleteView(generic.BulkDeleteView):
    queryset = SoftwareProduct.objects.all()
    filterset = filtersets.SoftwareProductFilterSet
    table = tables.SoftwareProductTable

netbox_slm/views/software_product_installation.py
from netbox.views import generic
from netbox_slm import filtersets, forms, tables
from netbox_slm.models import SoftwareProductInstallation
from utilities.views import register_model_view


@register_model_view(SoftwareProductInstallation, "list", path="", detail=False)
class SoftwareProductInstallationListView(generic.ObjectListView):
    queryset = SoftwareProductInstallation.objects.all()
    filterset = filtersets.SoftwareProductInstallationFilterSet
    filterset_form = forms.SoftwareProductInstallationFilterForm
    table = tables.SoftwareProductInstallationTable


@register_model_view(SoftwareProductInstallation)
class SoftwareProductInstallationView(generic.ObjectView):
    queryset = SoftwareProductInstallation.objects.all()


@register_model_view(SoftwareProductInstallation, "add", detail=False)
@register_model_view(SoftwareProductInstallation, "edit")
class SoftwareProductInstallationEditView(generic.ObjectEditView):
    queryset = SoftwareProductInstallation.objects.all()
    form = forms.SoftwareProductInstallationForm


@register_model_view(SoftwareProductInstallation, "delete")
class SoftwareProductInstallationDeleteView(generic.ObjectDeleteView):
    queryset = SoftwareProductInstallation.objects.all()


@register_model_view(SoftwareProductInstallation, "bulk_import", detail=False)
class SoftwareProductInstallationBulkImportView(generic.BulkImportView):
    queryset = SoftwareProductInstallation.objects.all()
    model_form = forms.SoftwareProductInstallationBulkImportForm


@register_model_view(SoftwareProductInstallation, "bulk_edit", path="edit", detail=False)
class SoftwareProductInstallationBulkEditView(generic.BulkEditView):
    queryset = SoftwareProductInstallation.objects.all()
    filterset = filtersets.SoftwareProductInstallationFilterSet
    table = tables.SoftwareProductInstallationTable
    form = forms.SoftwareProductInstallationBulkEditForm


@register_model_view(SoftwareProductInstallation, "bulk_delete", path="delete", detail=False)
class SoftwareProductInstallationBulkDeleteView(generic.BulkDeleteView):
    queryset = SoftwareProductInstallation.objects.all()
    filterset = filtersets.SoftwareProductInstallationFilterSet
    table = tables.SoftwareProductInstallationTable

netbox_slm/views/software_product_version.py
from netbox.views import generic
from netbox_slm import filtersets, forms, tables
from netbox_slm.models import SoftwareProductVersion
from utilities.views import register_model_view


@register_model_view(SoftwareProductVersion, "list", path="", detail=False)
class SoftwareProductVersionListView(generic.ObjectListView):
    queryset = SoftwareProductVersion.objects.all()
    filterset = filtersets.SoftwareProductVersionFilterSet
    filterset_form = forms.SoftwareProductVersionFilterForm
    table = tables.SoftwareProductVersionTable


@register_model_view(SoftwareProductVersion)
class SoftwareProductVersionView(generic.ObjectView):
    queryset = SoftwareProductVersion.objects.all()

    def get_extra_context(self, request, instance):
        installation_count = instance.get_installation_count()
        return {"installations": installation_count}


@register_model_view(SoftwareProductVersion, "add", detail=False)
@register_model_view(SoftwareProductVersion, "edit")
class SoftwareProductVersionEditView(generic.ObjectEditView):
    queryset = SoftwareProductVersion.objects.all()
    form = forms.SoftwareProductVersionForm


@register_model_view(SoftwareProductVersion, "delete")
class SoftwareProductVersionDeleteView(generic.ObjectDeleteView):
    queryset = SoftwareProductVersion.objects.all()


@register_model_view(SoftwareProductVersion, "bulk_import", detail=False)
class SoftwareProductVersionBulkImportView(generic.BulkImportView):
    queryset = SoftwareProductVersion.objects.all()
    model_form = forms.SoftwareProductVersionBulkImportForm


@register_model_view(SoftwareProductVersion, "bulk_edit", path="edit", detail=False)
class SoftwareProductVersionBulkEditView(generic.BulkEditView):
    queryset = SoftwareProductVersion.objects.all()
    filterset = filtersets.SoftwareProductVersionFilterSet
    table = tables.SoftwareProductVersionTable
    form = forms.SoftwareProductVersionBulkEditForm


@register_model_view(SoftwareProductVersion, "bulk_delete", path="delete", detail=False)
class SoftwareProductVersionBulkDeleteView(generic.BulkDeleteView):
    queryset = SoftwareProductVersion.objects.all()
    filterset = filtersets.SoftwareProductVersionFilterSet
    table = tables.SoftwareProductVersionTable

netbox_slm/templates/netbox_slm/installations_card_include.html
{% load helpers %}

<div class="card">
    <h2 class="card-header">
        Installations
{% if perms.netbox_slm.add_softwareproductinstallation %}
        <div class="card-actions">
            <a href="{% url 'plugins:netbox_slm:softwareproductinstallation_add' %}?{{ search_obj }}={{ object.pk }}" class="btn btn-ghost-primary btn-sm">
                <span class="mdi mdi-plus-thick" aria-hidden="true"></span> Add an installation
            </a>
        </div>
{% endif %}
    </h2>
{% if search_obj == "cluster" %}
{% htmx_table "plugins:netbox_slm:softwareproductinstallation_list" cluster_id=object.pk %}
{% elif search_obj == "device" %}
{% htmx_table "plugins:netbox_slm:softwareproductinstallation_list" device_id=object.pk %}
{% elif search_obj == "virtualmachine" %}
{% htmx_table "plugins:netbox_slm:softwareproductinstallation_list" virtualmachine_id=object.pk %}
{% endif %}
</div>

netbox_slm/templates/netbox_slm/softwarelicense.html
{% extends 'generic/object.html' %}
{% load buttons %}
{% load static %}
{% load helpers %}
{% load plugins %}

{% block content %}
<div class="row my-3">
	<div class="col col-md-6">
        <div class="card">
            <h5 class="card-header">
                Software License
            </h5>
            <table class="table table-hover attr-table">
                <tr>
                    <th scope="row">Name</th>
                    <td>{{ object.name }}</td>
                </tr>
                <tr>
                    <th scope="row">Description</th>
                    <td>{{ object.description }}</td>
                </tr>
                <tr>
                    <th scope="row">Type</th>
                    <td>{{ object.type }}</td>
                </tr>
                <tr>
                    <th scope="row">SPDX expression</th>
                    <td>{{ object.spdx_expression }}</td>
                </tr>
                <tr>
                    <th scope="row">Software Product</th>
                    <td>{{ object.software_product|linkify }}</td>
                </tr>
                <tr>
                    <th scope="row">Version</th>
                    <td>{{ object.version|linkify }}</td>
                </tr>
                <tr>
                    <th scope="row">Installation</th>
                    <td>{{ object.installation|linkify }}</td>
                </tr>
                <tr>
                    <th scope="row">Stored location</th>
{% if object.stored_location_url %}
                    <td><a href="{{ object.stored_location_url }}">{{ object.stored_location_txt }}</a></td>
{% else %}
                    <td>{{ object.stored_location_txt }}</td>
{% endif %}
                </tr>
                <tr>
                    <th scope="row">Start date</th>
                    <td>{{ object.start_date }}</td>
                </tr>
                <tr>
                    <th scope="row">Expiration date</th>
                    <td>{{ object.expiration_date }}</td>
                </tr>
                <tr>
                    <th scope="row">Support</th>
                    <td>{{ object.support }}</td>
                </tr>
                <tr>
                    <th scope="row">License amount</th>
                    <td>{{ object.license_amount }}</td>
                </tr>
            </table>
        </div>
{% include 'inc/panels/custom_fields.html' %}
{% include 'inc/panels/tags.html' %}
{% include 'inc/panels/comments.html' %}
{% plugin_left_page object %}
    </div>
</div>
<div class="row">
    <div class="col col-md-12">
{% plugin_full_width_page object %}
    </div>
</div>
{% endblock %}

netbox_slm/templates/netbox_slm/softwareproduct.html
{% extends 'generic/object.html' %}
{% load buttons %}
{% load static %}
{% load helpers %}
{% load plugins %}

{% block content %}
<div class="row my-3">
	<div class="col col-md-6">
        <div class="card">
            <h5 class="card-header">
                Software Product
            </h5>
            <table class="table table-hover attr-table">
                <tr>
                    <th scope="row">Name</th>
                    <td>{{ object.name }}</td>
                </tr>
                <tr>
                    <th scope="row">Description</th>
                    <td>{{ object.description }}</td>
                </tr>
                <tr>
                    <th scope="row">Manufacturer</th>
                    <td>{{ object.manufacturer|linkify }}</td>
                </tr>
                <tr>
                    <th scope="row">Versions</th>
                    <td>
{% for version in object.softwareproductversion_set.all %}
                        <a href="{% url 'plugins:netbox_slm:softwareproductversion' pk=version.pk %}" class="btn btn-sm">
                            {{ version }}
                        </a>
{% empty %}
                        None
{% endfor %}
                    </td>
                </tr>
                <tr>
                    <th scope="row">Installations</th>
                    <td>
{% for installation in object.softwareproductinstallation_set.all %}
                        <a href="{% url 'plugins:netbox_slm:softwareproductinstallation' pk=installation.pk %}" class="btn btn-sm">
                            {{ installation }}
                        </a>
{% empty %}
                        None
{% endfor %}
                    </td>
                </tr>
                <tr>
                    <th scope="row">Licenses</th>
                    <td>
{% for license in object.softwarelicense_set.all %}
                        <a href="{% url 'plugins:netbox_slm:softwarelicense' pk=license.pk %}" class="btn btn-sm">
                            {{ license }}
                        </a>
{% empty %}
                        None
{% endfor %}
                    </td>
                </tr>
            </table>
        </div>
{% include 'inc/panels/custom_fields.html' %}
{% include 'inc/panels/tags.html' %}
{% include 'inc/panels/comments.html' %}
{% plugin_left_page object %}
    </div>
</div>
<div class="row">
    <div class="col col-md-12">
{% plugin_full_width_page object %}
    </div>
</div>
{% endblock %}

netbox_slm/templates/netbox_slm/softwareproductinstallation.html
{% extends 'generic/object.html' %}
{% load buttons %}
{% load static %}
{% load helpers %}
{% load plugins %}

{% block content %}
<div class="row my-3">
	<div class="col col-md-6">
        <div class="card">
            <h5 class="card-header">
                Software Product Installation
            </h5>
            <table class="table table-hover attr-table">
{% if object.device %}
                <tr>
                    <th scope="row">Device</th>
                    <td>{{ object.device|linkify }}</td>
                </tr>
{% elif object.virtualmachine %}
                <tr>
                    <th scope="row">Virtual Machine</th>
                    <td>{{ object.virtualmachine|linkify }}</td>
                </tr>
{% else %}
                <tr>
                    <th scope="row">Cluster</th>
                    <td>{{ object.cluster|linkify }}</td>
                </tr>
{% endif %}
                <tr>
                    <th scope="row">Software Product</th>
                    <td>{{ object.software_product|linkify }}</td>
                </tr>
                <tr>
                    <th scope="row">Version</th>
                    <td>{{ object.version|linkify }}</td>
                </tr>
                <tr>
                    <th scope="row">Licenses</th>
                    <td>
{% for license in object.softwarelicense_set.all %}
                        <a href="{% url 'plugins:netbox_slm:softwarelicense' pk=license.pk %}" class="btn btn-sm">
                            {{ license }}
                        </a>
{% empty %}
                        None
{% endfor %}
                    </td>
                </tr>
            </table>
        </div>
{% include 'inc/panels/custom_fields.html' %}
{% include 'inc/panels/tags.html' %}
{% include 'inc/panels/comments.html' %}
{% plugin_left_page object %}
    </div>
</div>
<div class="row">
    <div class="col col-md-12">
{% plugin_full_width_page object %}
    </div>
</div>
{% endblock %}

netbox_slm/templates/netbox_slm/softwareproductversion.html
{% extends 'generic/object.html' %}
{% load buttons %}
{% load static %}
{% load helpers %}
{% load plugins %}

{% block content %}
<div class="row my-3">
	<div class="col col-md-6">
        <div class="card">
            <h5 class="card-header">
                Software Product Version
            </h5>
            <table class="table table-hover attr-table">
                <tr>
                    <th scope="row">Name</th>
                    <td>{{ object.name }}</td>
                </tr>
                <tr>
                    <th scope="row">Description</th>
                    <td>{{ object.description }}</td>
                </tr>
                <tr>
                    <th scope="row">Manufacturer</th>
                    <td>{{ object.software_product.manufacturer|linkify }}</td>
                </tr>
                <tr>
                    <th scope="row">Software Product</th>
                    <td>{{ object.software_product|linkify }}</td>
                </tr>
                <tr>
                    <th scope="row">Release date</th>
                    <td>{{ object.release_date }}</td>
                </tr>
                <tr>
                    <th scope="row">Documentation url</th>
{% if object.documentation_url %}
                    <td><a href="{{ object.documentation_url }}">{{ object.documentation_url }}</a></td>
{% else %}
                    <td>{{ object.documentation_url }}</td>
{% endif %}
                </tr>
                <tr>
                    <th scope="row">End of support</th>
                    <td>{{ object.end_of_support }}</td>
                </tr>
                <tr>
                    <th scope="row">Filename</th>
{% if object.file_link %}
                    <td><a href="{{ object.file_link }}">{{ object.filename }}</a></td>
{% else %}
                    <td>{{ object.filename }}</td>
{% endif %}
                </tr>
                <tr>
                    <th scope="row">File checksum</th>
                    <td>{{ object.file_checksum }}</td>
                </tr>
                <tr>
                    <th scope="row">Release type</th>
                    <td>{{ object.get_release_type_display }}</td>
                </tr>
                <tr>
                    <th scope="row">Installations</th>
                    <td>
{% for installation in object.softwareproductinstallation_set.all %}
                        <a href="{% url 'plugins:netbox_slm:softwareproductinstallation' pk=installation.pk %}" class="btn btn-sm">
                            {{ installation }}
                        </a>
{% empty %}
                        None
{% endfor %}
                    </td>
                </tr>
                <tr>
                    <th scope="row">Licenses</th>
                    <td>
{% for license in object.softwarelicense_set.all %}
                        <a href="{% url 'plugins:netbox_slm:softwarelicense' pk=license.pk %}" class="btn btn-sm">
                            {{ license }}
                        </a>
{% empty %}
                        None
{% endfor %}
                    </td>
                </tr>
            </table>
        </div>
{% include 'inc/panels/custom_fields.html' %}
{% include 'inc/panels/tags.html' %}
{% include 'inc/panels/comments.html' %}
{% plugin_left_page object %}
    </div>
</div>
<div class="row">
    <div class="col col-md-12">
{% plugin_full_width_page object %}
    </div>
</div>
{% endblock %}